spring.application.name=cloud-file-storage
spring.datasource.url=jdbc:postgresql://localhost:5432/clouddb
spring.datasource.username=cloudfile
spring.datasource.password=cloudfile
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.data.redis.database=0
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=cloudfile
spring.data.redis.timeout=6380
spring.session.store-type=redis
spring.minio.url=https://play.min.io
spring.minio.bucket=00000qweqwe
spring.minio.access-key=cloudfile
spring.minio.secret-key=cloudfile
